image: go_builder
matrix:
  - env: GO_VERSION=go1.9 PROJECT_PATH=github.com/cooperaj/starling-coinjar

before_install:
  - gvm install $GO_VERSION -B
  - gvm use $GO_VERSION --default
  - gvm linkthis $PROJECT_PATH

install:
  - cd $GOPATH/src/$PROJECT_PATH && go get ./...

script:
  - cd $GOPATH/src/$PROJECT_PATH && go test -v ./...