image: gvm_builder
matrix:
  - env: GO_VERSION=1.10
  - env: GO_VERSION=1.11 GO111MODULE=on

cache:
  - /home/abstruse/.gvm/versions

before_install:
  - gvm install $GO_VERSION

install:
  - if [[ -z $GO_VERSION ]]; then go get github.com/onsi/ginkgo/ginkgo; fi
  - if [[ -z $GO_VERSION ]]; then go get github.com/onsi/gomega/...; fi
  - go get ./...

script:
  - go test ./...