image: gvm_builder
matrix:
  - env: GO_VERSION=1.10
  - env: GO_VERSION=1.11 GO111MODULE=on

cache:
  - /home/abstruse/.gvm/versions

before_install:
  - env
  - gvm install $GO_VERSION

install:
  - if [[ -z $GO111MODULE ]]; then go get github.com/onsi/ginkgo/ginkgo; fi
  - if [[ -z $GO111MODULE ]]; then go get github.com/onsi/gomega/...; fi
  - go get ./...

script:
  - go test -v ./...
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker build -f Dockerfile -t cooperaj/starling-coinjar:latest .; fi
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker tag cooperaj/starling-coinjar:latest cooperaj/starling-coinjar:${ABSTRUSE_TAG}; fi
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker build -f Dockerfile.armhf -t cooperaj/armhf-starling-coinjar:latest .; fi
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker tag cooperaj/armhf-starling-coinjar:latest cooperaj/armhf-starling-coinjar:${ABSTRUSE_TAG}; fi

deploy:
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi
  - if [[ $ABSTRUSE_TAG != "null" ]]; then docker push cooperaj/armhf-starling-coinjar:latest; fi