image: gvm_builder
matrix:
  - env: GO_VERSION=1.10
  - env: GO_VERSION=1.11 GO111MODULE=on

cache:
  - /home/abstruse/.gvm/versions

before_install:
  - gvm install $GO_VERSION

install:
  #- [[ -z $GO111MODULE ]] go get github.com/onsi/ginkgo/ginkgo
  #- [[ -z $GO111MODULE ]] go get github.com/onsi/gomega/...
  - go get ./...

script:
  - [[ -z $GO111MODULE ]] ginkgo -r
  - [[ -n $GO111MODULE ]] go test ./...