image: go_builder
matrix:
  - env: GO_VERSION=go1.9 PROJECT_PATH=github.com/cooperaj/starling-coinjar
  - env: GO_VERSION=go1.10 PROJECT_PATH=github.com/cooperaj/starling-coinjar
  - env: GO_VERSION=go1.11 PROJECT_PATH=github.com/cooperaj/starling-coinjar

before_install:
  - gvm install $GO_VERSION -B
  - gvm use $GO_VERSION --default
  - gvm linkthis $PROJECT_PATH

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/go-bindata/go-bindata/...
  - cd $GOPATH/src/$PROJECT_PATH && go get ./...

script:
  - cd $GOPATH/src/$PROJECT_PATH && $GOPATH/bin/ginkgo -r